#!/bin/sh

#config system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.led_wan
uci commit system

#config network
uci set 'network.lan.ipaddr=192.168.10.253'
uci set 'network.lan.proto=static'
uci set 'network.lan.type=bridge'
uci set 'network.lan.gateway=192.168.10.1'
uci set 'network.lan.dns=192.168.10.1'
uci set 'network.lan.broadcast=192.168.10.255'
uci set 'network.lan.ipv6=off'
uci delete 'network.lan.ip6assign'
uci set 'network.lan.delegate=0'
uci set 'network.lan.force_link=0'
uci set 'network.wan.ipv6=0'
uci set 'network.wan.delegate=0'
uci delete 'network.wan6'
uci commit network

uci set 'dhcp.lan.ignore=1'
uci set 'dhcp.lan.dhcpv6=disabled'
uci set 'dhcp.lan.ra=disabled'
uci del dhcp.lan.ra
uci del dhcp.lan.ra_management
uci commit dhcp

exit 0
