#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

#config system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.led_wan
uci commit system

#config network
uci del network.wan
uci del network.wan6
uci commit network

uci set network.lan.ipaddr='192.168.10.253'
uci set network.lan.proto='static'
uci set network.lan.type='bridge'
uci set network.lan.ifname='eth0 eth1'
uci set network.lan.gateway='192.168.10.1'
uci set network.lan.dns='192.168.10.1'
uci set network.lan.broadcast='192.168.10.255'
uci del network.lan.ip6assign
uci set network.lan.delegate='0'
uci commit network

uci set dhcp.lan.ignore='1'
uci del dhcp.lan.ra
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ra_management
uci commit dhcp

exit 0
